version: '3.0'

services:
  mysql-test:
    image: mysql:8.0.17
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - mysql.env
    networks:
      - baeldung

  postgres-test:
    image: postgres:11.5
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: postgres.env
    networks:
      - baeldung

networks:
  baeldung:
    driver: bridge