#book:
#  service:
#    url: http://book.service.com

books-client:
  ribbon:
    eureka:
      enabled: false
  listOfServers: http://book.service.com
  ServerListRefreshInterval: 15000
  MaxAutoRetries: 3
  retryableStatusCodes: 503, 408